name: Vue + PlatformIO CI

on:
  push:
    branches: 
      - master
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Npm install
        run: npm install
        working-directory: ./vue


      - name: Npm build compressed esp32 app
        run: npm run buildNode
        working-directory: ./vue

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build Firmware for Esp32
        run: platformio run


      - name: Create date tag
        id: devtag
        run: echo "::set-output name=value::$(date +'dev-v%Y-%m-%d-%H-%M')"

      - name: Publish firmware Permanent
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .pio/build/esp32dev/firmware.bin
          asset_name: firmware.bin
          tag: ${{ steps.devtag.outputs.value  }}
          overwrite: true
          allowUpdates: true

      - name: Publish firmware Latest
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .pio/build/esp32dev/firmware.bin
          asset_name: firmware.bin
          tag: dev
          overwrite: true
          allowUpdates: true
      
      - name: Npm build Web App
        run: npm run build
        working-directory: ./vue

      - name: Deploy Web App
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue/dist
